import type { Metadata, Viewport } from "next";
import Script from "next/script";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import { WebVitals } from "@/components/WebVitals";
import CookieBanner from "@/components/CookieBanner";
import { serializeJsonLd } from "@/lib/seo/jsonLd";
import { DEFAULT_OG_IMAGES, DEFAULT_TWITTER_IMAGES } from "@/lib/seo/defaults";
import "./globals.css";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

const BASE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://yukujapan.com").replace(/\/+$/, "");

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: "Yuku Japan | Routed Japan Itineraries, Day by Day",
  description:
    "Your Japan trip, planned day by day. Routed itineraries with real transit times, sourced from Japan\u2019s official tourism boards.",
  openGraph: {
    title: "Yuku Japan | Routed Japan Itineraries, Day by Day",
    description:
      "Your Japan trip, planned day by day. Routed itineraries with real transit times, sourced from Japan\u2019s official tourism boards.",
    url: BASE_URL,
    siteName: "Yuku Japan",
    type: "website",
    locale: "en_US",
    // 1200×630 branded card generated by src/app/opengraph-image.tsx.
    // Detail pages (places, cities, guides) override with their own photo.
    images: DEFAULT_OG_IMAGES,
  },
  twitter: {
    card: "summary_large_image",
    title: "Yuku Japan | Routed Japan Itineraries, Day by Day",
    description:
      "Your Japan trip, planned day by day. Routed itineraries with real transit times, sourced from Japan\u2019s official tourism boards.",
    images: DEFAULT_TWITTER_IMAGES,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Yuku Japan",
  url: BASE_URL,
  logo: `${BASE_URL}/icon`,
  description:
    "Curated travel guides, itineraries, and inspiration for planning trips to Japan, built with local experts.",
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Yuku Japan",
  url: BASE_URL,
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${BASE_URL}/places?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://mbjcxrfuuczlauavashs.supabase.co" />
        <link rel="preconnect" href="https://cdn.sanity.io" />
      </head>
      <body className="min-h-[100dvh] antialiased" suppressHydrationWarning>
        <Script
          id="ld-organization"
          type="application/ld+json"
          strategy="beforeInteractive"
        >
          {serializeJsonLd(organizationJsonLd)}
        </Script>
        <Script
          id="ld-website"
          type="application/ld+json"
          strategy="beforeInteractive"
        >
          {serializeJsonLd(websiteJsonLd)}
        </Script>
        <GoogleAnalytics />
        <WebVitals />
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
